

spring.datasource.url=jdbc:mysql://localhost:3306/doc_ai_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Vinayinsta@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/Your_DataBase_Name(set your configuration)?createDatabaseIfNotExist=true
spring.datasource.username=set your configuration
spring.datasource.password=set your configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver





