
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/doc_ai_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Vinayinsta@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

=======
spring.datasource.url=jdbc:mysql://localhost:3306/Your_DataBase_Name(set your configuration)?createDatabaseIfNotExist=true
spring.datasource.username=set your configuration
spring.datasource.password=set your configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


>>>>>>> 6c245f4e818a2056b1a716baf74edfed472b129c
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

<<<<<<< HEAD
spring.servlet.multipart.max-file-size=10MB
=======

spring.servlet.multipart.max-file-size=10MB
>>>>>>> 6c245f4e818a2056b1a716baf74edfed472b129c
